platform :ios,'7.0'
inhibit_all_warnings!

pod "libchromium"

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libstdc++'
    end
  end
end
